In [1]:
import pickle
import numpy as np
import pandas as pd
import extractors

In [2]:
with open('saved_models/cnn_lstm_mfcc', 'rb') as f:
    cnn_lstm_mfcc = pickle.load(f)

In [21]:
test_file = 'test_samples/cough.mp3'
test_features = extractors.mfcc_extract(test_file)
test_features = np.array([test_features])

In [23]:
prediction = cnn_lstm_mfcc.predict(test_features)
prediction[0][0]

1/1 [==============================] - 0s 19ms/step


0.53850824

In [24]:
with open('saved_models/cnn_lstm_advanced', 'rb') as f:
    cnn_lstm_advn = pickle.load(f)

In [29]:
test_features1 = extractors.advanced_extract(test_file)
test_features1 = np.array([test_features1])

In [31]:
prediction1 = cnn_lstm_advn.predict(test_features1)
prediction1[0][0]

1/1 [==============================] - 0s 21ms/step


0.72314024

In [33]:
with open('saved_models/cnn_spect', 'rb') as f:
    cnn_spect = pickle.load(f)

In [56]:
test_features2 = extractors.melSpect_extract(test_file)
test_features2 = test_features2.reshape(1, 128, 1, 1)
test_features2

array([[[[3.38339239e-01]],

        [[2.14230582e-01]],

        [[2.19204217e-01]],

        [[6.51935697e-01]],

        [[2.80876470e+00]],

        [[2.03940296e+00]],

        [[8.18755031e-01]],

        [[5.09544671e-01]],

        [[1.88154674e+00]],

        [[5.24834347e+00]],

        [[1.19531784e+01]],

        [[1.84552116e+01]],

        [[1.78574886e+01]],

        [[1.03794651e+01]],

        [[1.10712290e+01]],

        [[9.59494209e+00]],

        [[7.54469347e+00]],

        [[1.75230045e+01]],

        [[5.65917473e+01]],

        [[1.32642040e+01]],

        [[2.11787891e+00]],

        [[6.89869976e+00]],

        [[8.97601223e+00]],

        [[6.93146849e+00]],

        [[1.60570679e+01]],

        [[2.38797283e+01]],

        [[1.84771309e+01]],

        [[1.01626987e+01]],

        [[6.56618500e+00]],

        [[6.69577074e+00]],

        [[7.21298265e+00]],

        [[5.13781881e+00]],

        [[3.27576590e+00]],

        [[2.31797719e+00]],

        [[2.12

In [57]:
prediction2 = cnn_spect.predict(test_features2)

1/1 [==============================] - 0s 17ms/step


In [58]:
prediction2

array([[5.23423e-08]], dtype=float32)

In [55]:
cnn_spect.input_shape

(None, 128, 1, 1)

In [59]:
test_file2 = 'test_samples/cough3.mp3'
test_features3 = extractors.melSpect_extract(test_file2)
test_features3 = test_features3.reshape(1, 128, 1, 1)

In [61]:
prediction3= cnn_spect.predict(test_features3)
prediction3

1/1 [==============================] - 0s 17ms/step


array([[0.8229142]], dtype=float32)

In [62]:
test_file3 = 'test_samples/laugh.mp3'
test_features4 = extractors.melSpect_extract(test_file3)
test_features4 =  test_features4.reshape(1, 128, 1, 1)

In [63]:
prediction4 = cnn_spect.predict(test_features4)
prediction4

1/1 [==============================] - 0s 14ms/step


array([[0.51250523]], dtype=float32)